# name of the software
name: MagiQL
# current version of the software
version: 0.0.1
# url of the download button
downloadUrl: https://github.com/magiql
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

   
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site 
 

# Build settings
markdown: kramdown



# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/magiql

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/magiql

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: magiql
  repo: magiql.github.com

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap